version: '3'
services:
  database:
    container_name: iijbootcamp-database
    image: mongo
    expose:
      - "27017"
  backend:
    container_name: iijbootcamp-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - database
    ports:
      - "8088:80"
